version: 2
jobs:
  build:
    docker:
      - image: golang:1.7.0
    working_directory: /go/src/github.com/Mayo-QIN/grunt
    steps:
      - checkout
      - run:
          name: "Build JUnit"
          command: |
            go get github.com/jstemmer/go-junit-report
            mkdir -p /tmp/test-results
      - run: |
          set -eu
          go test -v -race ./... | go-junit-report > /tmp/test-results/unit-tests.xml
      - store_test_results:
          path: /tmp/test-results          
          
