services:
  - endPoint: echo
    commandLine: ["echo", "@message"]
    description: print a message
    defaults:
      message: "Hi From Grunt"
  - endPoint: affine
    commandLine: ["./simpleReg", "-f","<fixed","-m", "<moving","-o", ">registered"]

    # commandLine: ["./simpleReg", "-d", "@dimension","-f","<fixed","-m", "<moving","-e", ">registered","-w",">warped", "-i",">inverse"]