#!/bin/bash
#
dim=3 # image dimensionality for now not an argument
AP="/tmp/bin/" # /home/yourself/code/ANTS/bin/bin/  # path to ANTs binaries
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=24  # controls multi-threading
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS

while getopts ":f:m:o:" opt; do
    case $opt in
        f)
            f=$OPTARG
            ;;
        m)  
            m=$OPTARG
            ;;   

        o)  
            out=$OPTARG
            ;; 
    esac
done 

# Now that we are done parsing options from the command line, shift
# the parsed parameters out of the command line arguments
shift $((OPTIND-1))

if [[ ! -s $f ]] ; then echo no fixed $f ; exit; fi
if [[ ! -s $m ]] ; then echo no moving $m ;exit; fi

nm1=` basename $f | cut -d '.' -f 1 `
nm2=` basename $m | cut -d '.' -f 1 `

reg=${AP}antsRegistration           # path to antsRegistration

its=10000x111110x11110
percentage=0.3
syn="100x100x50,-0.01,5"
mysetting=forproduction

its=1x0x0
percentage=0.1
syn="1x0x0,0,5"

nm=${D}${nm1}_fixed_${nm2}   # construct output prefix
echo affine $m $f outname is $nm am using setting $mysetting
$reg -d $dim -r [ $f, $m ,1]  \
                        -m mattes[  $f, $m , 1 , 32, regular, $percentage ] \
                         -t translation[ 0.1 ] \
                         -c [$its,1.e-8,20]  \
                        -s 4x2x1vox  \
                        -f 6x4x2 -l 1 \
                        -m mattes[  $f, $m , 1 , 32, regular, $percentage ] \
                         -t rigid[ 0.1 ] \
                         -c [$its,1.e-8,20]  \
                        -s 4x2x1vox  \
                        -f 3x2x1 -l 1 \
                        -m mattes[  $f, $m , 1 , 32, regular, $percentage ] \
                         -t affine[ 0.1 ] \
                         -c [$its,1.e-8,20]  \
                        -s 4x2x1vox  \
                        -f 3x2x1 -l 1 \
                        -m mattes[  $f, $m , 0.5 , 32 ] \
                        -m cc[  $f, $m , 0.5 , 4 ] \
                         -t SyN[ .20, 3, 0 ] \
                         -c [ $syn ]  \
                        -s 1x0.5x0vox  \
                        -f 4x2x1 -l 1 -u 1 -z 1 \
                       -o [${out},${out}_diff.nii.gz,${out}_inv.nii.gz]

# this is not the best way to do that, but since ANTs is creating diffrent filenames than the ones grunt is expecting i have to copy the files to correspond to the curl comand. 
echo ${out}

VAR=$m
DIR=$(dirname "${VAR}")
echo "${DIR}"
cp ${out}0GenericAffine.mat Affine.mat
cp ${out}1InverseWarp.nii.gz InverseWarp.nii.gz
cp ${out}_diff.nii.gz ${out}


echo ${DIR}/Affine.mat
echo ${DIR}/InverseWarp.nii.gz
echo ${out}
