// Code generated by go-bindata.
// sources:
// assets/template/email.txt
// assets/template/grunt.html
// assets/template/header.html
// assets/template/help.html
// assets/template/job.html
// assets/template/jobs.html
// assets/template/service.html
// assets/template/services.html
// README.md
// DO NOT EDIT!

package dassets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// templateEmailTxt reads file data from disk. It returns an error on failure.
func templateEmailTxt() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/email.txt"
	name := "template/email.txt"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateGruntHtml reads file data from disk. It returns an error on failure.
func templateGruntHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/grunt.html"
	name := "template/grunt.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateHeaderHtml reads file data from disk. It returns an error on failure.
func templateHeaderHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/header.html"
	name := "template/header.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateHelpHtml reads file data from disk. It returns an error on failure.
func templateHelpHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/help.html"
	name := "template/help.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateJobHtml reads file data from disk. It returns an error on failure.
func templateJobHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/job.html"
	name := "template/job.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateJobsHtml reads file data from disk. It returns an error on failure.
func templateJobsHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/jobs.html"
	name := "template/jobs.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateServiceHtml reads file data from disk. It returns an error on failure.
func templateServiceHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/service.html"
	name := "template/service.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templateServicesHtml reads file data from disk. It returns an error on failure.
func templateServicesHtml() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/assets/template/services.html"
	name := "template/services.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// readmeMdReadmeMd reads file data from disk. It returns an error on failure.
func readmeMdReadmeMd() (*asset, error) {
	path := "/Users/m112447/Drive/grunt/README.md"
	name := "README.md/README.md"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"template/email.txt": templateEmailTxt,
	"template/grunt.html": templateGruntHtml,
	"template/header.html": templateHeaderHtml,
	"template/help.html": templateHelpHtml,
	"template/job.html": templateJobHtml,
	"template/jobs.html": templateJobsHtml,
	"template/service.html": templateServiceHtml,
	"template/services.html": templateServicesHtml,
	"README.md/README.md": readmeMdReadmeMd,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"README.md": &bintree{nil, map[string]*bintree{
		"README.md": &bintree{readmeMdReadmeMd, map[string]*bintree{}},
	}},
	"template": &bintree{nil, map[string]*bintree{
		"email.txt": &bintree{templateEmailTxt, map[string]*bintree{}},
		"grunt.html": &bintree{templateGruntHtml, map[string]*bintree{}},
		"header.html": &bintree{templateHeaderHtml, map[string]*bintree{}},
		"help.html": &bintree{templateHelpHtml, map[string]*bintree{}},
		"job.html": &bintree{templateJobHtml, map[string]*bintree{}},
		"jobs.html": &bintree{templateJobsHtml, map[string]*bintree{}},
		"service.html": &bintree{templateServiceHtml, map[string]*bintree{}},
		"services.html": &bintree{templateServicesHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

